/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    pages: Page;
    categories: Category;
    media: Media;
    users: User;
    redirects: Redirect;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Blogcikkek és hírek. A publikált cikk a /cikk/slug címen jelenik meg, kinézetét az aktív téma adja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Rövid összefoglaló a listaoldalakra – és ha nincs külön meta leírás, a Google is ezt kapja.
   */
  excerpt?: string | null;
  /**
   * A cikk fejléce és a kártyák képe. Ajánlott: legalább 1200 px széles.
   */
  coverImage?: (number | null) | Media;
  /**
   * Klasszikus szerkesztő: fenti eszköztár + "/" jellel beszúró menü (kép, galéria, videó, CTA, idézet). Címsorokat H2-től lefelé használj – a H1 a cikk címe.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Üresen hagyva a címből generálódik. Csak kisbetű, szám és kötőjel.
   */
  slug?: string | null;
  category?: (number | null) | Category;
  author?: (number | null) | User;
  /**
   * Üresen hagyva az első publikáláskor automatikusan kitöltődik.
   */
  publishedAt?: string | null;
  /**
   * Keresőoptimalizálási beállítások. Üresen hagyott mezők esetén a motor értelmes alapértékeket használ (cím, kivonat, borítókép).
   */
  seo?: {
    /**
     * A Google találati listában megjelenő cím. Ideális hossz: 50–60 karakter.
     */
    metaTitle?: string | null;
    /**
     * A találati listában megjelenő leírás. Ideális hossz: 140–160 karakter, tartalmazza a fő kulcsszót.
     */
    metaDescription?: string | null;
    /**
     * Facebook/LinkedIn/WhatsApp megosztáskor megjelenő kép. Ajánlott méret: 1200×630 px. Ha üres, a borítókép lesz.
     */
    ogImage?: (number | null) | Media;
    /**
     * Csak akkor töltsd ki, ha a tartalom máshol jelent meg eredetileg, és arra szeretnél mutatni.
     */
    canonicalUrl?: string | null;
    /**
     * Bepipálva a Google nem indexeli ezt a tartalmat.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Feltöltéskor a motor automatikusan legenerálja a szükséges képméreteket (kártya, borító, megosztási kép).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A kép rövid leírása. Fontos a SEO-hoz és a képernyőolvasót használóknak – írd le, mi látható a képen.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cover?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * A cikkek témakörei – minden kategória saját listaoldalt kap (/kategoria/slug).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * A kategória-oldal bevezetője és meta leírása.
   */
  description?: string | null;
  /**
   * Üresen hagyva a címből generálódik. Csak kisbetű, szám és kötőjel.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Az admin felület felhasználói. A cikkeknél szerzőként is megjelennek.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * A cikkek szerzőjeként ez a név jelenik meg az oldalon.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Statikus oldalak: rólunk, kapcsolat, impresszum stb. A publikált oldal a /slug címen érhető el; a menübe az Admin → Menük alatt teheted ki.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Klasszikus szerkesztő: fenti eszköztár + "/" jellel beszúró menü (kép, galéria, videó, CTA, idézet).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Üresen hagyva a címből generálódik. Csak kisbetű, szám és kötőjel.
   */
  slug?: string | null;
  /**
   * Oldalépítő módban a tartalmat a /builder címen szerkesztheted (pl. http://localhost:3000/builder).
   */
  editorMode: 'richtext' | 'builder';
  /**
   * Keresőoptimalizálási beállítások. Üresen hagyott mezők esetén a motor értelmes alapértékeket használ (cím, kivonat, borítókép).
   */
  seo?: {
    /**
     * A Google találati listában megjelenő cím. Ideális hossz: 50–60 karakter.
     */
    metaTitle?: string | null;
    /**
     * A találati listában megjelenő leírás. Ideális hossz: 140–160 karakter, tartalmazza a fő kulcsszót.
     */
    metaDescription?: string | null;
    /**
     * Facebook/LinkedIn/WhatsApp megosztáskor megjelenő kép. Ajánlott méret: 1200×630 px. Ha üres, a borítókép lesz.
     */
    ogImage?: (number | null) | Media;
    /**
     * Csak akkor töltsd ki, ha a tartalom máshol jelent meg eredetileg, és arra szeretnél mutatni.
     */
    canonicalUrl?: string | null;
    /**
     * Bepipálva a Google nem indexeli ezt a tartalmat.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * SEO-létfontosságú: ha egy cikk URL-je megváltozik, itt vedd fel a régi címet, hogy a Google-ranking ne vesszen el.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Perjellel kezdődő útvonal, pl. /cikk/regi-cim
   */
  from: string;
  /**
   * Útvonal (/cikk/uj-cim) vagy teljes URL (https://...)
   */
  to: string;
  /**
   * Bepipálva 301-es (végleges), kipipálva 307-es (ideiglenes) átirányítás.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A kapcsolatűrlapon beküldött üzenetek – a legfrissebb legfelül.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * Melyik oldalon lévő űrlapról érkezett.
   */
  path?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  layout?: T;
  slug?: T;
  editorMode?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cover?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Az oldal neve, aktív téma, mérőkódok és közösségi linkek – egy helyen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * A főoldal fejlécében és az alap meta leírásban jelenik meg.
   */
  tagline?: string | null;
  /**
   * Ha üres, az oldal neve jelenik meg szövegként.
   */
  logo?: (number | null) | Media;
  /**
   * Váltáskor az egész oldal kinézete átáll – a tartalomhoz nem kell hozzányúlni.
   */
  theme: 'folyoirat' | 'studio' | 'magazin';
  footerText?: string | null;
  /**
   * Formátum: GTM-XXXXXXX. Ezen az egy konténeren keresztül köthető be a GA4, a Google Ads, a Meta Pixel, a TikTok Pixel és a LinkedIn Insight Tag – kódmódosítás nélkül.
   */
  gtmId?: string | null;
  /**
   * A Search Console "HTML-címke" hitelesítési módjánál kapott content érték (csak a kód, nem a teljes meta tag).
   */
  searchConsoleVerification?: string | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    /**
     * Nemzetközi formátumban, + és szóközök nélkül, pl. 36301234567. Kitöltve lebegő WhatsApp-gomb jelenik meg az oldalon.
     */
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Az oldal fejléc- és láblécmenüje. Ami itt nincs felvéve, az nem jelenik meg a menüben – a publikált oldalak persze linkről és a keresőből így is elérhetők.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Új menüpont a lenti gombbal, a sorrend a bal oldali fogantyúval húzva rendezhető.
   */
  header?:
    | {
        label: string;
        linkType?: ('page' | 'custom') | null;
        page?: (number | null) | Page;
        /**
         * Pl. /kategoria/hirek vagy https://kulso-oldal.hu
         */
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Új menüpont a lenti gombbal, a sorrend a bal oldali fogantyúval húzva rendezhető.
   */
  footer?:
    | {
        label: string;
        linkType?: ('page' | 'custom') | null;
        page?: (number | null) | Page;
        /**
         * Pl. /kategoria/hirek vagy https://kulso-oldal.hu
         */
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  theme?: T;
  footerText?: T;
  gtmId?: T;
  searchConsoleVerification?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
        linkedin?: T;
        youtube?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}